---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: vault-ubuntu-1604
    image: brandfrisch/ubuntu-16.04:latest
    privileged: true
    command: /lib/systemd/systemd
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
  options:
    D: true
  lint:
    name: ansible-lint
    options:
      r: /usr/local/src/ansible-lint/rules
scenario:
  name: default
verifier:
  name: goss
